### ISSUE TITLE
Opt-out from cluster-claim controller for light-weighting managed-cluster installation

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/registration#114]
in some cases, we don't have sufficient permission to install cluster-scoped resources such as CRDs (i.e. cluster-claim) into the managed-cluster. for now, i can basically think of 2 approaches to opt-out from cluster-claim controller from running:

- 1. a simple approach will be adding a flag `--disable-cluster-claim-controller` which stops the spoke-agent from list-watching cluster-claim. 
- 2. a more generic approach is adding a flag `--controllers` which is a list of names of the controllers we expect to run. (i had a initial locally, and it will be working like the following). but the flag will only apply to spoke-agent, i wonder if we want to move further to do the similar change to hub controllers. and additionally the dark side is this approach is that AFAICT there're some mandatory controllers not expected to be disabled by any chance:

```
      --controllers stringArray                  The names of controllers to run (default [ManagedClusterController,ManagedClusterHealthCheckController,ManagedClusterLeaseController,BootstrapClientCertForHubController,ClientCertForHubController,ClusterClaimController,HubKubeconfigSecretController,ManagedClusterCreatingController])
```

@qiujian16 for thoughts?

**Comment by qiujian16** [comment]
We could consider things like `--feature-gates="ClusterClaim=false"` also?
