### ISSUE TITLE
Add the ability to auth to managed clusters without using CSR 

### ISSUE THREAD

**Issue by rbakhtaraev** [open-cluster-management-io/registration#185]
For some reason we don't have ability for enabling CSR in our clusters. Can you add another way to authenticate managed clusters without using CSR, like sa-token/secret with kubeconfig?

**Comment by dangorst1066** [comment]
Also observed this when using EKS as the ocm hub cluster.

1. EKS does not have the `kubernetes.io/kube-apiserver-client` signer
1. EKS uses a custom signer `beta.eks.amazonaws.com/app-serving` that does not support client auth (as auth is ultimately delegated to IAM), so while a CSR can be approved, no certificate will ever be issued that requests client auth usage.

**Comment by apphe** [comment]
@dgorst Do you have a plan to contribute the implementation? Is it possible to merge codes before Oct 21 which is OCM 0.9 release?

**Comment by mikeshng** [comment]
Hi @rbakhtaraev we now support standalone control plane which allows the hub cluster to host the OCM control plane with cert client auth enable. Please see free to check it out and see if you are able to solve your use case.

**Comment by qiujian16** [comment]
we are having an separate issue to implement eks auth support

/close
