### ISSUE TITLE
Is registration supported multi-arch image?

### ISSUE THREAD

**Issue by ivan-cai** [open-cluster-management-io/registration#208]
Hi, Is registration/work/placement/registration-operator/subscription/channel supported multi-arch image? I have not found the arm image

**Comment by yue9944882** [comment]
cc @qiujian16 

regarding the multi-arch build support as discussed before

**Comment by qiujian16** [comment]
not yet, I think we should start planning this for 0.8.0 release. Maybe we need a parent issue that covers all related component that needs to support arm image.

**Comment by ivan-cai** [comment]
> not yet, I think we should start planning this for 0.8.0 release. Maybe we need a parent issue that covers all related component that needs to support arm image.

@qiujian16 Hi, could we support multi-arch in 0.8.0 release(all components, e.g. registration/work/placement/subscription/channel...)? And when will 0.8.0 release be released？

**Comment by qiujian16** [comment]
I think we could. We haven't decided the date yet. Most likely on early July.

**Comment by qiujian16** [comment]
this is done already
/close
