### ISSUE TITLE
Memory usage keeps increasing when add-on registration config changes frequently

### ISSUE THREAD

**Issue by elgnay** [open-cluster-management-io/registration#219]
When registration config of an add-on changes frequently, for example 1 time per second, registration-agent will create a new CSR based on the new config on hub cluster. The number of CSRs may increase quickly. Since the registration-agent caches all those CSRs, that may cause the memory usage keep increasing. A mechanism is needed to limit the rate of CSR creation for each addon.

**Comment by qiujian16** [comment]
we have added a limit on csr that can be created. 

/close
