### ISSUE TITLE
[RFE] during import cluster auto detect microshift vendor/version

### ISSUE THREAD

**Issue by wangjun1974** [open-cluster-management-io/registration#257]
MicroShift is a project that is exploring how OpenShift and Kubernetes can be optimized for small form factor and edge computing.
* https://microshift.io/docs/home/
* https://microshift.io/docs/getting-started/

microshift is currently recognized as OpenShiftV3 when registering a cluster. This affects Observability to install monitoring stack for microshift.

**Comment by qiujian16** [comment]
This is implemented in ACM not upstream

/close
