### ISSUE TITLE
Support V1beta1 CSR API Compatibility

### ISSUE THREAD

**Issue by promacanthus** [open-cluster-management-io/registration#258]
When the kubernetes version of hub cluster is less than 1.19, there is no v1 CSR API. The registration-controller running in the hub cluster will got the following error message.

```shell
E0627 02:27:32.103218       1 reflector.go:138] k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1.CertificateSigningRequest: failed to list *v1.CertificateSigningRequest: the server could not find the requested resource
```

To solve this problem, we can enable compatibility with the v1beta1 CSR feature gates in the  registration-controller.

**Comment by qiujian16** [comment]
fixed

/close
