### ISSUE TITLE
Specify ExpirationSeconds in CSR request

### ISSUE THREAD

**Issue by youhangwang** [open-cluster-management-io/registration#311]
v1CSRControl create a csr request without ExpirationSeconds. the expiration time of the signed certificate depends on the --cluster-signing-duration in controller manager.

can we add a expirationSeconds param in the function to specify a expiration time to create a csr?

https://github.com/open-cluster-management-io/registration/blob/fc792f3816ed1e2f2d0609a5c0ac69da32ed2ab9/pkg/clientcert/certificate.go#L216

**Comment by skeeey** [comment]
yeah, we may add an option for registration agent to configure this

/cc @qiujian16

**Comment by qiujian16** [comment]
+1

**Comment by youhangwang** [comment]
I can make this change as the first contribution to OCM proj ;)
