### ISSUE TITLE
Redirect for go imports is missing.

### ISSUE THREAD

**Issue by msfrucht** [open-cluster-management-io/registration#323]
Cannot import the go library because the redirect to /registration is missing.

wget [open-cluster-management.io/registration](http://open-cluster-management.io/registration)
 cat index.html
`<html><head><meta name=go-import content="[open-cluster-management.io/clusteradm](http://open-cluster-management.io/clusteradm) git https://github.com/open-cluster-management-io/clusteradm"><meta name=go-source content="[open-cluster-management.io/clusteradm](http://open-cluster-management.io/clusteradm)     https://github.com/open-cluster-management-io/clusteradm [https://github.com/open-cluster-management-io/clusteradm/tree/main{/dir}](https://github.com/open-cluster-management-io/clusteradm/tree/main%7B/dir%7D) [https://github.com/open-cluster-management-io/clusteradm/blob/main{/dir}/{file}#L{line}](https://github.com/open-cluster-management-io/clusteradm/blob/main%7B/dir%7D/%7Bfile%7D#L{line})"></head></html> (edited)`

**Comment by skeeey** [comment]
@msfrucht this repo is moved to the [ocm](https://github.com/open-cluster-management-io/ocm), please use ocm repo instead of registration, thanks

**Comment by qiujian16** [comment]
I think this is due to the refactor of website...Please let me know if it is ok to import open-cluster-management.io/ocm instead? This repo is no longer updated, but we can add this back to import link if deps change is too hard.

**Comment by msfrucht** [comment]
Adding back to the import worked. Thank you. I have notified our team that we need to migrate.

**Comment by qiujian16** [comment]
this is added. Please note this repo will be archived.
