### ISSUE TITLE
Improve documentation of double checking time synchronization on the clusters

### ISSUE THREAD

**Issue by alosadagrande** [open-cluster-management-io/registration#80]
I've been struggling for a couple of days with a problem between my hub and spoke cluster. Basically, I was seeing how the configuration applied from my Git repository was being created, removed and created continuously. It did not happen when using policies or at least I did not notice.

Finally, with the ACM team help I've been able to spot the culprit, which was that the spoke and hub cluster were not correctly time synchronized. Actually chrony configuration was not set up correctly. This was caused by the clusterCondition of my placementrules:

```
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
```

**Comment by skeeey** [comment]
add a notice in the readme
